# Generated by Django 4.2.1 on 2023-05-27 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0003_alter_user_department_alter_user_role_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='knowledge_base_app.category', verbose_name='Родительская категория'),
        ),
    ]
